project:
  type: website
  output-dir: docs

website:
  title: "Medhat Farwati's Website"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Education & Training
        href: Education_Training.qmd
      - text: Blog
        href: blog/Blog.qmd
      - text: Study 1 Analyses
        href: study 1 analyses.qmd
      - text: Study 2 Analyses
        href: study 2 analyses.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2

